# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCarrera', models.CharField(max_length=250)),
                ('sigla', models.CharField(max_length=20)),
                ('universidad', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MallaCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMalla', models.CharField(max_length=250)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Carrera')),
            ],
        ),
    ]
